---
#
# Use the following to create an environment file for secrets:
# ansible-playbook -i inventory/prod create_environment_file.yaml --ask-vault-pass
#
- name: Create a local environment file so notebooks can pick up API keys
  hosts: local
  vars:
    source_folder: smartsheet-notebooks
  tasks:
    - name: Create the file from template
      ansible.builtin.template:
        src: env-file.j2
        dest: "{{ source_folder }}/.env-{{ environment_code }}"
